[package]
name = "vulkan_backend"
version = "0.1.0"
edition = "2021"

[dependencies]
glam = "0.28.0"
tokio = { version = "1.38.0", features = ["full"] }
vulkano = { version = "0.34.1" }
vulkano-shaders = "0.34.0"
winit = { version = "0.30.3", features = ["rwh_05"] }
